deployment:
  tasks:
    - export DEPLOYPATH=/home/calleeol/fluidsms.com
    - /bin/npm ci --prefix $DEPLOYPATH
    - /bin/npm run build --prefix $DEPLOYPATH
    - /bin/touch $DEPLOYPATH/tmp/restart.txt
